// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkcclisjkrllgcdxefik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrY2NsaXNqa3JsbGdjZHhlZmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Mzc4MjUsImV4cCI6MjA2NjQxMzgyNX0.OOELuJ90idmWwv7iPyjz4TFmG5KoM_SerZY8wtvEPuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);